import { Bell } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { NotificationList } from "@/components/notification-list";
import { requireProfile } from "@/lib/auth";
import { getNotifications } from "@/lib/queries";

export default async function AdminNotificationsPage() {
  await requireProfile(["admin"]);
  const notifications = await getNotifications();
  return (
    <>
      <PageHeader title="Notifications" description="System notifications generated by reviews and important account activity." icon={Bell} />
      <NotificationList notifications={notifications} />
    </>
  );
}
